### ISSUE TITLE
Converter Options Need to be More Predicatable

### ISSUE THREAD

**Issue by ChadSikorra** [ldaptools/ldaptools#32]
Currently Attribute Converter options set in the schema are not consistent. There is a lot of redundancy and repetition in how they are defined. There should be a set structure in how the converter options are defined. It should always follow something like:

```yaml
        converter_options:
            value_to_dn:
                 # This is a special key that, if defined, will always be applied first
                 _default:
                    attribute: name
                 # This level should always be the attribute name for the options.
                archiveDatabase:
                    # This level should always be the name => value pairs of options.
                    base_dn: "%_configurationnamingcontext_%"
                    attribute: cn
                    filter:
                        objectClass: msExchMDB
```

This way we can always expect that the options will only be for the context of the attribute being converted. The options in the converters can then more naturally define their defaults explicitly in the class `$options` array. This also helps handle case-insensitivity for the attributes in a more efficient way outside of the converter, so the converter doesn't have to care about figuring out the attribute specific options it needs.
